spring:
  application:
    name: oneservice-zuul-service
server:
  port: 8762
eureka:
  instance:
    preferIpAddress: true
  serviceurl:
    defaultzone: http://${eureka.host}:8761/eureka/
  client:
    registerWithEureka: true
    fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
